config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'
  resources :movies do
    resources :comments
    resources :likes
  end
  resources :users do
    member do
     get :subscribe, :subscribers
    end
  end
  resources :subscribes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,length: {minimum: 5}
  validates :user, presence: true
  validates :img, presence: true
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  mount_uploader :img, ImageUploader
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :subscriber, class_name: "User"
  belongs_to :subscribe, class_name: "User"
  validates :subscriber_id, presence: true
  validates :subscribe_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  validates :profile, length: { maximum: 200 }
  has_many :movies
  has_many :likes, dependent: :destroy
  has_many :liked_movies, through: :likes, source: :movie
  has_many :subscribe_subscribes, foreign_key: "subscriber_id", class_name: "Subscribe", dependent: :destroy
  has_many :subscribes, through: :subscribe_subscribes
  has_many :subscriber_subscribes, foreign_key: "subscribe_id", class_name: "Subscribe", dependent: :destroy
  has_many :subscribers, through: :subscriber_subscribes
  def already_liked?(movie)
    self.likes.exists?(movie_id: movie.id)
  end

  def subscribe?(other_user)
    subscribe_subscribes.find_by(subscribe_id: other_user.id)
  end

  def subscribe!(other_user)
    subscribe_subscribes.create!(subscribe_id: other_user.id)
  end

  def unsubscribe!(other_user)
    subscribe_subscribes.find_by(subscribe_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation, :image, :profile]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "dhh",password: "secret",only: :destroy
    def create
        @movie = Movie.find(params[:movie_id])
        @comment = @movie.comments.create(comment_params)
        redirect_to movie_path(@movie)
    end

    def destroy
        @movie = Movie.find(params[:movie_id])
        @comment = @movie.comments.find(params[:id])
        @comment.destroy
        redirect_to movie_path(@movie)
    end

    private
     def comment_params
        params.require(:comment).permit(:commenter, :body)
     end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(movie_id: params[:movie_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @like = Like.find_by(movie_id: params[:movie_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def index
      @movies = Movie.all
  end

  def show
      @movie = Movie.find(params[:id])
      @like = Like.new
  end

  def new
      @movie = Movie.new
  end

  def edit
      @movie = Movie.find(params[:id])
  end

  def create
      @movie = Movie.new(movie_params)
      @movie.user_id = current_user.id

      if @movie.save
          redirect_to @movie
      else
          render 'new'
      end
  end

  def update
      @movie = Movie.find(params[:id])
      respond_to do |format|
          if @movie.update(movie_params) && @movie.img.recreate_versions!
              format.html {redirect_to @movie, notice: 'movie was susseccfully updated.'}
              format.json{ head :no_content }
          else
              format.html {render 'edit'}
              format.json{ render json: @movie.errors, status: :unprocessable_entity }
          end
      end
  end

  def destroy
      @movie = Movie.find(params[:id])
      @movie.destroy

      redirect_to movies_path
  end

  def ensure_correct_user
      @post = Post.find_by(id:params[:id])
      if @post.user_id != @current_user.id
        flash[:notice] = "権限がありません"
        redirect_to movies_path
    end
  end

  private
      def movie_params
          params.require(:movie).permit(:title, :text, :img, :remove_img, :user_id)
      end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  def create
      @user = User.find(params[:subscribes][:subscribe_id])
      current_user.subscribe!(@user)
      redirect_to @user
  end

  def destroy
      @user = Subscribe.find(params[:id]).subscribe
      current_user.unsubscribe!(@user)
      redirect_to
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def subscribe
    @user  = User.find(params[:id])
    @users = @user.subscribes
    render 'show_follow'
  end

  def subscribers
    @user  = User.find(params[:id])
    @users = @user.subscribers
    render 'show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/comments/_comment.html.erb
<p>
 <strong>Commenter</strong>
 <%= comment.commenter %>
</p>

<p>
 <strong>Comment</strong>
 <%= comment.body %>
</p>

<p>
 <%= link_to '✖', [comment.movie, comment],method: :delete, data:{confirm: 'Are you sure?' }%>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @movie, @movie.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter ,class:'form-control'%>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body ,class:'form-control'%>
    </p>
    <p>
      <%= form.submit 'Comment', class:'btn btn-outline-warning' %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Top</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to 'Profile Edit', edit_user_registration_path, class:'nav-link' %><span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to current_user.username, user_path(current_user.id),class:'nav-link' %>
      </li>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path %>
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </ul>
  </div>
</nav>
    <!-- ここに追加 -->
    <div class="container">
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<h3>New book</h3>
  <%= form_with scope: :movie, url: movies_path, local: true do |form| %>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title,class:'form-control' %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text,class:'form-control' %>
    </p>

    <p>
      <%= form.label :images %><br />
      <%= form.file_field :img %>
    </p>

    <p><%= form.check_box :remove_img %>画像を削除する</p>

    <p>
      <%= form.submit 'Submit',class:'btn btn-outline-primary' %>
    </p>
  <% end %>

app/views/movies/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="text-right">
<%= link_to 'New', new_movie_path ,class:'btn btn-outline-dark'%>
</div>
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-3">
     <div class="card mt-2">
      <div class="card-img-top">
       <iframe id="<%= movie.title %>" title="<%= movie.title %>" width="100%" height="100%" src="<%= movie.img.url %>"></iframe>
      </div>
      <div class="card-body">
       <%= movie.title %><br><%= movie.user.username %>-<%= link_to 'Read More',movie_path(movie) %>
      </div>
      </div>
    </div>
  <% end %>
</div>
  

app/views/movies/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p>
 <strong>Title:</strong>
 <%= @movie.title %>
</p>

<iframe id="<%= @movie.title %>" title="<%= @movie.title %>" width="100%" height="500px" src="<%= @movie.img.url %>"></iframe>

<p>
 <strong>Text:</strong>
 <%= @movie.text %> - <%= @movie.user.username %>
</p>

<div class="form-inline">
<% if current_user.already_liked?(@movie) %>
  <%= button_to '★', movie_like_path(@movie), method: :delete,class:'btn btn-warning' %>
<% else %>
  <%= button_to '☆', movie_likes_path(@movie) ,class:'btn btn-outline-warning' %>
<% end %>
<h3>:<%= @movie.likes.count %></h3>
</div>
<h2>Gooded Users</h2>
<% @movie.liked_users.each do |user| %>
  <ul>
   <li><%= user.username %></li>
  </ul>
<% end %>

<strong>Comments</strong>
<%= render @movie.comments %>

<%= render "comments/form" %>

app/views/users/_follow.html.erb
<%= form_for(current_user.subscribe_subscribes.build(subscribe_id: @user.id)) do |form| %>
    <div><%= form.hidden_field :subscribe_id %></div>
    <%= form.submit "Follow" %>
  <% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="subscribe_form">
<% if current_user.subscribe?(@user) %>
  <%= render 'unsubscribe' %>
<% else %>
  <%= render 'subscribe' %>
<% end %>
</div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= subscribe_user_path(@user) %>">
    <strong id="subscribe" class="stat">
      <%= @user.subscribes.count %>
    </strong>
    subscribe
  </a>
  <a href="<%= subscribers_user_path(@user) %>">
    <strong id="subscribes" class="stat">
      <%= @user.subscribers.count %>
    </strong>
    subscribers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.subscribe_subscribes.find_by(subscribe_id: @user.id), html: { method: :delete }) do |form| %>
    <%= form.submit "Unfollow" %>
  <% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.email %></a>
  <hr>
<% end %>

app/views/users/show.html.erb
<div class="row">
<div class="col-sm-4">
   <img src="<%= @user.image %>" width="200px" height="200px" style="border-radius:50%;object-fit:cover;"><br>
</div>
<div class="col">
<p>Profile</p>
ユーザー名:<%= @user.username %>さん<br>
メールアドレス:<%= @user.email %><br>
プロフィール:<%= @user.profile %><br>

<%= render 'follow_form' %>
<%= render 'stats' %>
</div>
</div>

<h2>My movie</h2>
<div class="row">
<% @user.movies.each do |movie| %>
  <div class="col-sm-3">
   <div class="card">
    <div class="card-img-top">
    <iframe src="<%= movie.img.url %>" width="100%" height="100%"></iframe>
    </div>
    <div class="card-body">
     <a href="/movies/<%= movie.id %>"><%= movie.text %></a><br>
     <%= link_to 'Edit',edit_movie_path(movie) ,class:'btn btn-outline-success' %>
     <%= link_to 'Destroy',movie_path(movie),method: :delete, data: {confirm: 'Are you sure?'},class:'btn btn-outline-danger' %>
    </div>
   </div>
  </div>
<% end %>
</div>
<h3>Good movie</h3>
<% @user.liked_movies.each do |movie| %>
  <%= movie.user.email %>
  <%= movie.text %><br>
<% end %>

<%= link_to 'UserArchive', users_path %>

app/views/users/show_follow.html.erb
<% @user.subscribes.each do |user| %>
    <table>
    <tr>
      <td><%= user.username %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>

    </table>
    <% end %>

app/views/users/show_follower.html.erb
<% @user.subscribers.each do |user| %>
    <table>
    <tr>
      <td><%= user.username %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>

    </table>
    <% end %>